version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
    # volumes:
    #   - D:\Projects\Test\db:/var/lib/postgresql/data
  
  web:
    build: .
    
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    
    #   - .:/code
    
    ports:
      - "8000:8000"
    depends_on:
      - db
# volumes:
#   dbdata: